# General settings
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[window]
option_as_alt = "Both"
startup_mode = "Maximized"

[scrolling]
history = 100000
# multiplier = 3

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"

[selection]
save_to_clipboard = true

# [terminal]
# osc53 = "OnlyCopy"

[[keyboard.bindings]]
key = "C"
mods = "Super"
mode = "AppCursor|AppKeypad|Search|Alt|Vi"
action = "Copy"
[[keyboard.bindings]]
key = "V"
mods = "Super"
mode = "AppCursor|AppKeypad|Search|Alt|Vi"
action = "Paste"
