[general]
live_config_reload=true

[env]
TERM="xterm-256color"
[font]
size=18

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
option_as_alt="Both"


[selection]
save_to_clipboard=true

[[keyboard.bindings]]
key="Delete"
chars="\u001b[3~"
